### PR TITLE
Removing 'animatable' option on the UI properties

### PR DESCRIPTION
**Pull request by plachenko**
I wasn't able to figure this out yesterday but this patch removes the default 'animatable' option in the UI properties as a safegaurd. I don't feel users would want to keyframe any of these properties.

### CODE REVIEW

**Comment by SirDifferential** [comment]
Is there something in the Blender plugin guidelines about this kind of thing? I seem to remember back in the 2.5 days the motto was something about being able to animate everything in UI.

**Comment by plachenko** [comment]
I'm not sure if there are any hard-set rules against keeping UI elements animatable. It just doesn't seem intuitive to allow a user to key frame most of these properties. Port and Address doesn't seem to be intended for animation for instance and object type won't change unless you refresh the collection hierarchy which seems like a good way to crash blender... (I haven't tried it to be honest)

It doesn't hurt to keep them 'animatable' I suppose-- it just seems like a safegaurd for users that might accidentally press 'i' inadvertently on two separate frames and have no idea why the plugin might seem broken.

**Comment by SirDifferential** [comment]
I think we can keep it animatable. Thanks for the suggestion though!

**Comment by plachenko** [comment]
Sounds good

**Pull request closed without merging**
