### PR TITLE
I5 - 2.8 Changes to NI-Mate plugin

### LINKED ISSUE #5: Update Blender plugin to Blender 2.8
Once the Blender 2.8 Python changes are set in stone, go through the plugin and make it work with the new Blender version. We'll have to host two versions from then on, keeping the old version available for users of Blender < 2.8

Links:

https://en.blender.org/index.php/Dev:2.8/
https://en.blender.org/index.php/Dev:2.8/Source/Migration#Python_API
https://en.blender.org/index.php/Dev:2.8/Source/Python/UpdatingScripts
https://en.blender.org/index.php/Dev:2.8/Source/LayersCollections/API-Changes

### PR DESCRIPTION
**Pull request by plachenko**
This pull request adds needed changes to work with NI-Mate and Blender 2.8. I've changed some code based on this comment: https://github.com/Delicode/NI-mate-plugins/issues/5#issuecomment-447692701 This also removes blender game engine functionality since the bge is now deprecated and the new blender 'interactive mode' has yet to come. 

I've only done light testing so I can't attest that all code works fine, but the purpose was to get this up and running with 2.8.

resolves #5

### CODE REVIEW

**Comment by SirDifferential** [comment]
Thanks for this - I'll go through this once we have a moment to look at this stuff.

**Comment by plachenko** [comment]
Would you mind if I expanded a bit on this branch? I've been reading up on blender's [gpu api](https://docs.blender.org/api/blender2.8/gpu.html) and think I could send the sensor feed to the view port display through a shader. I'm not fully sure if I could set the feed as a texture on a material yet though but I believe at least displaying feed data is possible. 

I would really like to capture point cloud data but I'm not sure about how you would do that with ni mate-- my understanding is that it only sends skeletal tracking info over the port, not depth data.

**Comment by SirDifferential** [comment]
NI mate only sends the skeleton data over OSC. The Spout/Syphon feeds include the depth feed which can be used to extract point cloud information.

**Comment by SirDifferential** [comment]
I'm accepting this pull request as it is and then submitting a few changes on top of it later. Thank for your valuable contribution.

**Comment by plachenko** [comment]
No problem! I still think the new gpu module should be able to draw on screen to replicate the BGE feed textures but I honestly haven't gotten to the point of parsing OSC data yet.

**Comment by SirDifferential** [comment]
I took a look at this https://docs.blender.org/api/blender2.8/gpu.html#d-image but the general consensus around the office was that without the game engine, the feeds themselves are of questionable value. The feeds were mostly useful when you had something approaching a full screen game in Blender, but with the feeds just existing in the viewport, they aren't all that useful. Technically Eevee is trying to be a game engine of sorts on its own, though.

**Pull request merged**
